# Generated by Django 4.2.26 on 2025-11-17 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('walk', 'Walk'), ('run', 'Run'), ('cycle', 'Cycle'), ('other', 'Other')], max_length=20)),
                ('steps', models.BigIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
